services:
  protocol-encoder:
    build: .
    container_name: protocol-encoder
    environment:
      - BA_PORT=8080
      - BA_ENCODERS_JAPAN_OFFSET=49015212
      - BA_ENCODERS_GLOBAL_OFFSET=103003304
    ports:
      - "8080:8080"
    restart: unless-stopped
