emulator:
  pool_size: 10
  timeout: 30            # Timeout in seconds for each encoding operation

encoders:
  japan:
    binary: "libraries/com.YostarJP.BlueArchive/libil2cpp.so"
    offset: "libraries/com.YostarJP.BlueArchive/offset.txt"
    aliases:
      - "j"
      - "jp"
      - "jpn"
    # pool_size: 10          # Optional: Override emulator pool_size
    # timeout: 30            # Optional: Override emulator timeout
  global:
    binary: "libraries/com.nexon.bluearchive/libil2cpp.so"
    offset: "libraries/com.nexon.bluearchive/offset.txt"
    aliases:
      - "g"
      - "gl"
    # pool_size: 10          # Optional: Override emulator pool_size
    # timeout: 30            # Optional: Override emulator timeout
