package main

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"
)

const (
	formatVersion     = 1
	valuesPerLine     = 9
	bodyDigestPrefix  = "// tablegen-body-sha256: "
	generatedFileMode = 0o644
)

const tableSourceTemplate = `package {{.PackageName}}

import protos {{printf "%q" .ImportPath}}

var protocolTable = map[protos.Protocol]*[routeCount]uint32{
{{range .Rows}}	{{.Protocol}}: {
{{range .ValueLines}}		{{.}}
{{end}}	},
{{end}}}
`

type metadata struct {
	packageName  string
	version      string
	libraryHash  [sha256.Size]byte
	offset       uint64
	protocolHash [sha256.Size]byte
}

type templateData struct {
	PackageName string
	ImportPath  string
	Rows        []templateRow
}

type templateRow struct {
	Protocol   int32
	ValueLines []string
}

func (m metadata) headerPrefix() []byte {
	return fmt.Appendf(nil,
		"// Code generated by protocol-tablegen. DO NOT EDIT.\n// tablegen-package: %s\n// tablegen-version: %s\n// tablegen-library-sha256: %x\n// tablegen-offset: %#x\n// tablegen-protocol-sha256: %x\n// tablegen-format-version: %d\n",
		m.packageName, m.version, m.libraryHash, m.offset, m.protocolHash, formatVersion,
	)
}

func readOutput(path string, required bool) ([]byte, error) {
	source, err := os.ReadFile(path)
	if err == nil {
		return source, nil
	}
	if errors.Is(err, os.ErrNotExist) && !required {
		return nil, nil
	}
	return nil, fmt.Errorf("read generated output %q: %w", path, err)
}

func validCache(source, prefix []byte) bool {
	if !bytes.HasPrefix(source, prefix) {
		return false
	}
	remainder := source[len(prefix):]
	lineEnd := bytes.IndexByte(remainder, '\n')
	if lineEnd < len(bodyDigestPrefix) || lineEnd+1 >= len(remainder) || remainder[lineEnd+1] != '\n' {
		return false
	}
	digestText := remainder[len(bodyDigestPrefix):lineEnd]
	if !bytes.HasPrefix(remainder, []byte(bodyDigestPrefix)) || len(digestText) != sha256.Size*2 {
		return false
	}
	body := remainder[lineEnd+2:]
	digest := sha256.Sum256(body)
	if !bytes.Equal(digestText, fmt.Appendf(nil, "%x", digest)) {
		return false
	}
	formatted, err := format.Source(body)
	return err == nil && bytes.Equal(formatted, body)
}

func render(cfg config, meta metadata, protocols []uint32, result extraction) ([]byte, error) {
	data := templateData{
		PackageName: cfg.packageName,
		ImportPath:  "github.com/arisu-archive/" + cfg.packageName + "-protos/protos",
		Rows:        make([]templateRow, 0, len(result.rows)),
	}
	for _, protocol := range protocols {
		row := result.rows[protocol]
		if row == nil {
			continue
		}
		data.Rows = append(data.Rows, templateRow{
			Protocol:   int32(protocol),
			ValueLines: formatValueLines(row[:]),
		})
	}

	tmpl, err := template.New("table").Parse(tableSourceTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse generated source template: %w", err)
	}
	var body bytes.Buffer
	if err := tmpl.Execute(&body, data); err != nil {
		return nil, fmt.Errorf("execute generated source template: %w", err)
	}
	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated body: %w", err)
	}
	digest := sha256.Sum256(formatted)
	source := append([]byte(nil), meta.headerPrefix()...)
	source = append(source, bodyDigestPrefix...)
	source = fmt.Appendf(source, "%x\n\n", digest)
	source = append(source, formatted...)
	return source, nil
}

func formatValueLines(values []uint32) []string {
	lines := make([]string, 0, (len(values)+valuesPerLine-1)/valuesPerLine)
	for start := 0; start < len(values); start += valuesPerLine {
		end := min(start+valuesPerLine, len(values))
		line := make([]byte, 0, valuesPerLine*12)
		for index, value := range values[start:end] {
			if index > 0 {
				line = append(line, ' ')
			}
			line = fmt.Appendf(line, "0x%08x,", value)
		}
		lines = append(lines, string(line))
	}
	return lines
}

func writeAtomic(path string, data []byte) (err error) {
	directory := filepath.Dir(path)
	info, err := os.Stat(directory)
	if err != nil {
		return fmt.Errorf("inspect output directory %q: %w", directory, err)
	}
	if !info.IsDir() {
		return fmt.Errorf("output directory %q is not a directory", directory)
	}
	temporary, err := os.CreateTemp(directory, "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return fmt.Errorf("create temporary output: %w", err)
	}
	temporaryPath := temporary.Name()
	isClosed := false
	keepTemporary := true
	defer func() {
		if !isClosed {
			err = errors.Join(err, temporary.Close())
		}
		if keepTemporary {
			removeErr := os.Remove(temporaryPath)
			if removeErr != nil && !errors.Is(removeErr, os.ErrNotExist) {
				err = errors.Join(err, fmt.Errorf("remove temporary output: %w", removeErr))
			}
		}
	}()
	if err := temporary.Chmod(generatedFileMode); err != nil {
		return fmt.Errorf("set temporary output mode: %w", err)
	}
	if _, err := temporary.Write(data); err != nil {
		return fmt.Errorf("write temporary output: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		return fmt.Errorf("sync temporary output: %w", err)
	}
	closeErr := temporary.Close()
	isClosed = true
	if closeErr != nil {
		return fmt.Errorf("close temporary output: %w", closeErr)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("replace output %q: %w", path, err)
	}
	keepTemporary = false
	return nil
}
