package main

import (
	"bytes"
	"testing"
)

const generatedLineLimit = 120

func TestRenderOmitsIdentityProtocols(t *testing.T) {
	var values [routeCount]uint32
	for route := range values {
		values[route] = uint32(1000 + route)
	}

	source, err := render(
		config{packageName: "arona", version: "1.2.3"},
		metadata{packageName: "arona", version: "1.2.3"},
		[]uint32{1, 2},
		extraction{rows: map[uint32]*[routeCount]uint32{2: &values}},
	)
	if err != nil {
		t.Fatalf("render() error = %v, want nil", err)
	}
	if bytes.Contains(source, []byte("\t1:")) {
		t.Errorf("render() contains identity protocol 1:\n%s", source)
	}
	if bytes.Contains(source, []byte(": nil")) {
		t.Errorf("render() contains a nil row:\n%s", source)
	}
	if !bytes.HasPrefix(source, []byte("// Code generated by protocol-tablegen. DO NOT EDIT.\n")) {
		t.Errorf("render() lacks generated-file header:\n%s", source)
	}
	wantValues := []byte("\t\t0x000003e8, 0x000003e9, 0x000003ea, 0x000003eb, 0x000003ec, 0x000003ed, 0x000003ee, 0x000003ef, 0x000003f0,\n\t\t0x000003f1,")
	if !bytes.Contains(source, wantValues) {
		t.Errorf("render() lacks override protocol 2:\n%s", source)
	}
	if bytes.Contains(source, []byte("tableVersion")) {
		t.Errorf("render() contains unused tableVersion:\n%s", source)
	}
	if !bytes.Contains(source, []byte("// tablegen-format-version: 1\n")) {
		t.Errorf("render() lacks format version 1:\n%s", source)
	}
	for _, line := range bytes.Split(source, []byte{'\n'}) {
		if len(line) > generatedLineLimit {
			t.Errorf("render() line length = %d, want <= %d:\n%s", len(line), generatedLineLimit, line)
		}
	}
}
